name: Java CI/CD with Maven - Build, Test, and Deploy WAR

on:
  push:
    branches: [main, feature-luong]
    paths:
      - "src/main/**"
      - "src/test/**"
  pull_request:
    branches: [main]
    paths:
      - "src/main/**"
      - "src/test/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Run Tests
        run: mvn test
      - name: Verify with Maven
        run: mvn clean verify
      - name: Build with Maven
        run: mvn package
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: servlet-war
          path: target/*.war
          if-no-files-found: error
